version: "3"
services:
  rabbitmq:
    image: "rabbitmq:management"
    restart: always
    ports:
      - "5672:5672" # Port pour les connexions AMQP
      - "15672:15672" # Port pour l'interface de gestion RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: "CodeRunner" # Utilisateur par défaut
      RABBITMQ_DEFAULT_PASS: "admin" # Mot de passe par défaut
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia
volumes:
  rabbitmq-data:
