version: "3"
name: code-runner
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  database:
    image: mariadb
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coderunner
    volumes:
      - database-data:/var/lib/mysql
volumes:
  redis-data:
  database-data:
